name: WinRDP
on: workflow_dispatch
jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 350
    steps:
      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0
          Set-ItemProperty -Path ('HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp') -Name UserAuthentication -Value 0
          netsh advfirewall firewall set rule group="remote desktop" new enable=Yes
          net user runner P@ssw0rd! /add
          net user runneradmin P@ssw0rd!
          net localgroup "Remote Desktop Users" runner /add
          net localgroup "Remote Desktop Users" runneradmin /add
          net localgroup "Administrators" runner /add

      - name: Tunnel via Pinggy
        shell: bash
        run: |
          while true; do
            ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -p 443 -R0:localhost:3389 tcp@free.pinggy.io 2>&1 | tee -a /tmp/pinggy.log
            sleep 5
          done
